diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -220,13 +220,16 @@ dump_ptrlists: | $(PTRLISTS_TEXT)

 # Tests
-.PHONY: test_tilemaps test_attribmaps
+.PHONY: test_tilemaps test_attribmaps test_tilesets

 test_tilemaps:
 	$(PYTHON) $(SCRIPT)/test_maps.py "$(TILEMAP_PREBUILT)"

 test_attribmaps:
 	$(PYTHON) $(SCRIPT)/test_maps.py "$(ATTRIBMAP_PREBUILT)"

+test_tilesets:
+	$(PYTHON) $(SCRIPT)/test_tilesets.py "$(TILESET_PREBUILT)"
+
 #Make directories if necessary
